# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17eua6_spCx9A7D_pDAXLF0xLRXdCYe03

# Aplicación Proyecto Final
"""

import joblib
import numpy as np
import pandas as pd
import streamlit as st
import shap
import matplotlib.pyplot as plt
from pathlib import Path
import tensorflow as tf
import os


#Configuración sitio
st.set_page_config(
    page_title="Predicción con Machine Learning",
    layout="centered"
)
#Funcion para cargar

BASE_DIR = Path(__file__).resolve().parent.parent

ruta_xgb = BASE_DIR / "models" / "modelo_xgb.joblib"

modelo_xgb = joblib.load(ruta_xgb)


#Valores barrios
barrios = ['Can Baró', 'Diagonal Mar i el Front Marítim del Poblenou',
       'Horta', 'Hostafrancs', 'Navas', 'Pedralbes', 'Porta',
       'Provençals del Poblenou', 'Sant Andreu', 'Sant Antoni',
       'Sant Gervasi - Galvany', 'Sant Gervasi - la Bonanova',
       'Sant Martí de Provençals',
       'Sant Pere, Santa Caterina i la Ribera', 'Sants', 'Sants - Badal',
       'Sarrià', 'Vallcarca i els Penitents',
       'Vallvidrera, el Tibidabo i les Planes',
       'Vilapicina i la Torre Llobeta', 'el Baix Guinardó',
       'el Barri Gòtic', 'el Besòs i el Maresme',
       "el Camp d'en Grassot i Gràcia Nova", "el Camp de l'Arpa del Clot",
       'el Carmel', 'el Clot', 'el Coll', 'el Congrés i els Indians',
       'el Fort Pienc', 'el Guinardó',
       'el Parc i la Llacuna del Poblenou', 'el Poble Sec', 'el Poblenou',
       'el Putxet i el Farró', 'el Raval', 'el Turó de la Peira',
       "l'Antiga Esquerra de l'Eixample", 'la Barceloneta', 'la Bordeta',
       "la Dreta de l'Eixample", "la Font d'en Fargues",
       'la Font de la Guatlla', 'la Guineueta', 'la Marina de Port',
       'la Maternitat i Sant Ramon', "la Nova Esquerra de l'Eixample",
       'la Prosperitat', 'la Sagrada Família', 'la Sagrera', 'la Salut',
       'la Teixonera', 'la Verneda i la Pau',
       'la Vila Olímpica del Poblenou', 'la Vila de Gràcia', 'les Corts',
       'les Roquetes', 'les Tres Torres']


#Interfaz
st.title("Aplicación de Predicción")
st.write(
    "Introduce los datos para obtener una predicción "
    "utilizando los modelos entrenados."
)

with st.form("Barrio"):
  Lag_7 = st.number_input("Ocupación hace 7 días", 0.0, 1.0, 0.4)
  Lag_14 = st.number_input("Ocupación hace 14 días", 0.0, 1.0, 0.4)
  Lag_28 = st.number_input("Ocupación hace 28 días", 0.0, 1.0, 0.4)
  mes = st.selectbox(
        "Mes",
        options=list(range(1, 13)),
        format_func=lambda x: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"][x - 1]
    )

  dia_semana = st.selectbox(
        "Día de la semana",
        options=list(range(7)),
        format_func=lambda x: ["Lunes", "Martes", "Miércoles", "Jueves","Viernes", "Sábado", "Domingo"][x]
    )
  neighbourhood_cleansed = st.selectbox("Barrio", options=barrios)
  enviar = st.form_submit_button("Predecir")


#Predecir en caso de que usuario envie los datos
if enviar:
  fila = pd.DataFrame([{
      "lag_7": Lag_7,
      "lag_14": Lag_14,
      "lag_28": Lag_28,
      "day_of_week": mes,
      "month": dia_semana,
      "neighbourhood_cleansed": neighbourhood_cleansed

  }])

  #Predicción XGBoost
  pred_xgb = modelo_xgb.predict(fila)
  pre = modelo_xgb.named_steps["preprocessor"]
  clf = modelo_xgb.named_steps["model"]


  #Recultados
  st.subheader("Resultados")
  st.metric("Predicción XGBoost:", f"{pred_xgb}:.1%")

  #SHAP Values
  datos_trans = pre.transform(fila)
  explainer = shap.TreeExplainer(clf)
  shap_values = explainer(datos_trans)
  fig, ax = plt.subplots()
  shap.plots.bar(shap_values[0],max_display=10)
  ax.set_title("Importancia de las variables - XGBoost")
  st.pyplot(fig)
  plt.close(fig)